config/routes.rb
PhishingFramework::Application.routes.draw do

	devise_for :admins

	# image tracking routes.
	get '/reports/image/:uid.png' => 'reports#image'

	# only allow emails to be send from POST request
	post '/email/preview_email/:id' => 'email#preview', as: 'preview_email'
	post '/email/test_email/:id' =>    'email#test', as: 'test_email'
	post '/email/launch_email/:id' =>  'email#launch', as: 'launch'

	# only allow deletion from POST requests
	get '/campaigns/delete_smtp_entry/:id' => 'campaigns#list'

	get "reports/list"
	get "reports/show"
	get "reports/delete"

	get "tools/emails" => "tools#emails"
	get "tools/show_emails/:id" => "tools#show_emails", as: 'show_emails'
	post "tools/enumerate_emails" => "tools#enumerate_emails"
	delete "tools/emails/:id" => "tools#destroy_email", as: 'destroy_email'
	get "tools/download_emails/:id" => "tools#download_emails", as: "download_emails"
	get "tools/import_emails" => "tools#import_emails"

	resources :campaigns do
		collection do
			get 'options'
			get 'home'
			get 'list'
			get 'aboutus'
			get 'victims'
			delete 'destroy'
		end
		member do
			post 'update_settings'
			post 'clear_victims'
		end
	end

	resources :blasts, only: [:show], shallow: true

	resources :templates do
		collection do
			get 'list'
			get 'restore'
			get 'edit_email'
			get 'update_attachment'
			delete 'destroy'
		end
	end

	resources :reports do
		collection do
			get 'list'
			get 'stats'
			get 'results'
			get 'download_logs'
			get 'download_stats'
			get 'apache_logs'
			get 'smtp'
			get 'passwords'
			post 'results'
			delete 'clear'
		end
		member do
			get 'download_excel'
		end
	end

	resources :admin do
		collection do
			get 'list'
			get 'global_settings'
			put 'update_global_settings'
		end
		member do
			get 'logins'
			post 'approve'
			post 'revoke'
			delete 'destroy'
		end
	end

  resources :clones do
  	member do
  		get 'download'
  		get 'preview'
  	end
  end

  resources :tools

	root :to => 'campaigns#home'

	match 'access', :to => 'access#menu', as: 'access'

	require 'sidekiq/web'

	authenticate :admin do
		mount Sidekiq::Web => '/sidekiq'
	end

	require 'sidekiq/api'
	match "queue-status" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.size < 100 ? "OK" : "UHOH" ]] }

	mount LetterOpenerWeb::Engine, at: 'letter_opener'

	match ':controller(/:action(/:id))(.:format)'
end

app/views/templates/_form.html.erb
<%= error_messages_for(@template) %>

<table id="template-table" class="table borderless">
  <tr>
    <th>Name</th>
    <td><span class="ui-icon ui-icon-help" title="Template name to distinguish itself"></span></td>
    <td><%= f.text_field(:name, required: true, class: "form-control") %></td>
 </tr>
  <tr>
    <th>Description</th>
    <td><span class="ui-icon ui-icon-help" title="Describe the details of the phishing campaign"></span></td>
    <td><%= f.text_area(:description, :size => "31x2", class: "form-control") %></td>
  </tr>
  <tr>
    <th>Notes</th>
    <td>
      <span class="ui-icon ui-icon-help" title="Enter any notes or details pertaining to the phishing template"></span>
    </td>
    <td><%= f.text_area(:notes, :size => "31x2", class: "form-control") %></td>
  </tr>
  <tr>
    <th>Index</th>
    <td>
      <span class="ui-icon ui-icon-help" title="This is the file displayed at the root URL. Defaults to index.html"/>
    </td>
    <td><%= f.text_field(:directory_index, class: "form-control") %></td>
  </tr>
</table>
<h3>Template Files</h3>

<div id="attachments">
  <%= f.fields_for :attachments, f.object.attachments.order(:function) do |attachment_form| %>
    <div class="row form-group">
      <div class="col-xs-2">
        <%= attachment_form.link_to_remove "Remove" %>
      </div>
      <div class="col-xs-2">
        <%= link_to attachment_form.object[:file], edit_email_templates_path(attachment_form.object[:id]) unless attachment_form.object[:file].nil? %>
      </div>
      <div class="col-xs-4">
        <%= attachment_form.select(:function, %w(website email attachment), {}, {class: "form-control"}) %>
      </div>
      <div class="col-xs-4">
        <%= attachment_form.file_field :file, class: 'form-control btn btn-eefault btn-file' %>
      </div>
    </div>
  <% end %>
</div>
<%= f.link_to_add "Add attachment", :attachments, "data-target" => "#attachments" %>

app/views/templates/_new.html.erb
<%= error_messages_for(@template) %>

<%= form_for(:template, :url => {:action => 'create'}) do |f| %>
  <table calss="table borderless" summary="Template Form fields">
    <tr>
      <th>Name</th>
      <td><span class="ui-icon ui-icon-help" title="Template name to distinguish itself"></span></td>
      <td><%= f.text_field(:name, required: true, class: "form-control") %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><span class="ui-icon ui-icon-help" title="Describe the details of the phishing campaign"></span></td>
      <td><%= f.text_area(:description, :size => "31x2", class: "form-control") %></td>
    </tr>
  </table>
  <br>
  <%= submit_tag("Create Template", class: 'btn btn-primary') %>
<% end %>

app/views/templates/_restore.html.erb
<%= error_messages_for(@template) %>
<% @page_title = "Restore Template" %>

<%= form_tag({action: :upload}, multipart: true) do %>
  <%= file_field_tag 'restore_template', class: 'btn btn-file', required: 'true', class: "form-control" %>
  <p></p>
  <%= submit_tag("Restore Template", class: 'btn btn-primary') %>
<% end %>

app/views/templates/edit.html.erb
<% @page_title = "Update Template" %>

<%= link_to("<< Back to List", {:action => 'list'}, :class => 'back-link') %>

<div class='page-header'>
  <h2>Update Phishing Template</h2>
</div>
<div class="template update">
	<%= nested_form_for @template, :html => {:multipart => true} do |f| %>
	<%= render(:partial => "form", :locals => {:f => f}) %>
	<p>
		<%= submit_tag("Update Template", class: 'btn btn-primary') %>
	</p>
	<% end %>
</div>

app/views/templates/edit_email.html.erb
<% @page_title = "Edit Template File" %>

<%= link_to("<< Back", 
            edit_template_path(@attachment.attachable_id), 
            :class => 'back-link') %>

<h2>Edit Attachment - <%= File.basename(@attachment.file.to_s) %></h2>

<div class='row'>
	<div class='col-md-12'>
		<%= form_for(:attachment, :url => {:action => 'update_attachment', :format => params[:format]}) do |f| %>
			<div class="form-buttons">
				<%= submit_tag("Save", class: 'btn btn-primary') %>
			</div>

			<%= text_area_tag("attachment_content", @attachment_content, size: "130x32") %>
		<% end %>
	</div>
</div>

app/views/templates/list.html.erb
<% @page_title = "Phishing Templates" %>

<div class='page-header'>
  <h2>Templates</h2>
</div>

<div id="template-buttons">
  <button class="btn btn-default" data-toggle="modal" data-target="#createTemplate">
    Create
  </button>
  <button class="btn btn-default" data-toggle="modal" data-target="#restoreTemplate">
    Restore
  </button>
</div>

<table id="templates" class="table table-striped table-hover table-condensed">
  <thead>
    <tr class="header">
      <th></th>
      <th>Name</th>
      <th>Description</th>
      <th>Index</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @templates.each do |template| %>
    <tr>
      <td><span class='glyphicon glyphicon-tags'></span></td>      
      <td><%= template.name %></td>
      <td><%= truncate(template.description) %></td>
      <td><%= template.index_file %></td>
      <td class="actions">
        <%= link_to("<span class='glyphicon glyphicon-edit'></span>".html_safe,
              {:action => 'edit', :id => template.id}, data: {placement: 'bottom'},
              class: 'btn btn-primary btn-xs', rel: 'tooltip', title: 'Edit Template') %>
        <%= link_to("<span class='glyphicon glyphicon-search'></span>".html_safe,
              {:action => 'show', :id => template.id}, data: {placement: 'bottom'},
              class: 'btn btn-default btn-xs', rel: 'tooltip', title: 'Show Template') %>
        <%= link_to("<span class='glyphicon glyphicon-retweet'></span>".html_safe,
              {:action => 'copy', :id => template.id}, data: {placement: 'bottom'},
              class: 'btn btn-default btn-xs', rel: 'tooltip', title: 'Copy Template') %>
        <%= link_to("<span class='glyphicon glyphicon-download-alt'></span>".html_safe,
              {:action => 'backup', :id => template.id}, data: {placement: 'bottom'},
              class: 'btn btn-default btn-xs', rel: 'tooltip', title: 'Backup Template') %>
        <%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe, 
              template_path(template), method: :delete,
              confirm: 'Are you sure you want to permanently delete this campaign?',
              class: 'btn btn-danger btn-xs', rel: 'tooltip',
              data: {placement: 'bottom'}, title: 'Delete Template' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<!-- Create Template Modal -->
<div class="modal fade" id="createTemplate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create Phishing Template</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "new" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Restore Template Modal -->
<div class="modal fade" id="restoreTemplate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Restore Phishing Template</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "restore" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/templates/new.html.erb
<% @page_title = "New Template" %>

<%= link_to("<< Back to List", {:action => 'list'}, :class => 'back-link') %>

<div class="page-header">
  <h2>New Phishing Template</h2>
</div>

<div class="template show">

  <%= image_tag('template.png', :size => '50x50') %>
  <%= nested_form_for(@template) do |f| %>

      <%= render(:partial => "form", :locals => {:f => f}) %>
      <p>
        <%= submit_tag("Create Template", :class => 'btn btn-default') %>
      </p>
  <% end %>
</div>

app/views/templates/preview_email.html.erb
<h2><%= @template.name %></h2>

<div class='preview'>
	<p><%= @preview.join.html_safe %></p>
<div>

app/views/templates/restore.html.erb
<%= error_messages_for(@template) %>
<% @page_title = "Restore Template" %>

<%= link_to("<< Back to List", {:action => 'list'}, :class => 'back-link') %>

<div class="page-header">
	<h2>Restore Phishing Template</h2>
</div>

<%= form_tag({action: :upload}, multipart: true) do %>
	<%= file_field_tag 'restore_template' %>
	<p></p>
	<%= submit_tag("Restore Template", class:'btn btn-default') %>
<% end %>

app/views/templates/show.html.erb
<% @page_title = "Template Details" %>

<%= link_to("<< Back to List", {:action => 'list'}, :class => 'back-link') %>

<div class="template show">
  <h2>Template Details</h2>
  <%= image_tag('template.png', :size => '35x35') %>

  <table class="table" summary="template detail view">
    <tr>
      <th>ID</th>
      <td><%= @template.id %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td><%= @template.name %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @template.description %></td>
    </tr>
    <tr>
      <th>Notes</th>
      <td><%= @template.notes %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @template.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @template.updated_at %></td>
    </tr>
    <tr>
      <th>Website Files</th>
      <td>
        <% @template.website_files.each do |www| %>
            <p>
              <%= link_to www[:file], www.file.url %>
              <% if www.function == 'website-index' %>
                <small>*</small>
              <% end %>
            </p>
        <% end %>
      <p><small>* - Index file</small></p>
      </td>
    </tr>
    <tr>
      <th>Email Files</th>
      <td>
        <% @template.email_files.each do |email| %>
            <p>
              <%= link_to email[:file], email.file.url %>
            </p>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>Preview</th>
      <td>
        <% if @images.any? %>
            <% @images.each do |image| %>
                <%= image[:file] %>
                <br/>
                <%= link_to(image_tag(image.file.url), image.file.url) %>
                <br/><br/>
            <% end %>
        <% else %>
            No preview images<br/>
            Add images to <%= @template.location %>
        <% end %>
      </td>
    </tr>
  </table>

</div>